- name: Setup Frontend
  hosts: all
  become: yes
  tasks:
    - name: Installing Nginx Server
      ansible.builtin.yum:
        name: nginx
        state: latest

 - name: remove directory
   ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

 - name: create directory
   ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
       src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
       dest: /usr/share/nginx/html
       remote_src: yes
       
    - name: Copy file with owner and permissions
     ansible.builtin.copy:
      src: /srv/myfiles/foo.conf
      dest: /etc/foo.conf










#echo -e "\e[33mRemoving Old App content\e[0m"
#rm -rf /usr/share/nginx/html/* &>>/tmp/roboshop.log
#stat_check $?

#echo -e "\e[33mDownloading Frontend Content\e[0m"
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>/tmp/roboshop.log
#stat_check $?

#echo -e "\e[33mExtract Frontend Content\e[0m"
#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip &>>/tmp/roboshop.log
#stat_check $?

# -e "\e[33mUpdate Frontend Configuration\e[0m"
#cp /home/centos/Roboshop-Project/roboshop.conf /etc/nginx/default.d/roboshop.conf &>>/tmp/roboshop.log
#stat_check $?

#echo -e "\e[33mStarting Nginx Server\e[0m"
#systemctl enable nginx &>>/tmp/roboshop.log
#systemctl restart nginx &>>/tmp/roboshop.log
# $?