- name: Configure erlang repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/{{ item }} | bash
  loop:
    - erlang/script.rpm.sh
    - rabbitmq-server/script.rpm.sh

- name: install Rabbitmq
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: start rbbitmq server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add application user
  community.rabbitmq.rabbitmq_user:
    user: {{ lookup('aws_ssm', 'roboshop.dev.rabbitmq.amqp_user', region='us-east-1') }}
    password: {{ lookup('aws_ssm', 'roboshop.dev.rabbitmq.amqp_pass', region='us-east-1') }}
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
